Drop explicit requeues for OpenStackAnsibleEE
openstack-k8s-operators/dataplane-operator pull request #170
Opened 2023-04-26 19:54 UTC by slagle

- Move nova deployment execution to deployment.Deploy
- Drop explicit requeues for OpenStackAnsibleEE

2023-04-26 20:47 UTC, fao89 commented on pkg/deployment/deployment.go
> +	nodes *dataplanev1beta1.OpenStackDataPlaneNodeList,
sweet!

2023-04-26 20:47 UTC, fao89 commented
+2

2023-04-27 06:26 UTC, stuggi commented on pkg/deployment/deployment.go
> +	logger := helper.GetLogger()
redundant? above there is already `log`

2023-04-27 15:19 UTC, fultonj requested changes
I tested this locally in my environment and it works correctly. 

I request however, that the redundant variable `logger` be removed since we have `log`. Thanks.

2023-04-27 15:19 UTC, fultonj commented on controllers/openstackdataplanerole_controller.go
> -		// Call DeployNovaExternalCompute individually for each node
ack, remove creating the NovaExternalCompute CR from within the controller code and create it instead in deployment.go

2023-04-27 16:38 UTC, slagle commented on pkg/deployment/deployment.go
> +	logger := helper.GetLogger()
Done.

2023-04-27 16:39 UTC, slagle commented on pkg/deployment/deployment.go
> +		logger.Info("Skipping execution of Ansible for ConfigureCephClient because extraMounts does not have an extraVolType of Ceph.")
#
Done.

2023-04-27 16:39 UTC, slagle commented on pkg/deployment/deployment.go
> +		logger.Info("Nova Status", "NovaExternalCompute", node.Name, "IsReady", novaExternalCompute.IsReady())
Done.

2023-04-27 16:39 UTC, slagle commented on pkg/deployment/deployment.go
> +		logger.Info("Not all NovaExternalCompute ReadyConditions are true.")
Done.

2023-04-27 17:33 UTC, fultonj approved these changes
/lgtm Thanks!

2023-04-27 17:37 UTC, merged