CSV: Set operator-type: non-standalone
openstack-k8s-operators/dataplane-operator pull request #281
Opened 2023-07-10 19:38 UTC by dprince

This should hide the dataplane package/bundle in the OpenShift console as we only want the main OpenStack operator to show up there.

2023-07-10 19:40 UTC, abays approved these changes
/lgtm

2023-07-10 22:41 UTC, bshephar requested changes
I'm not too sure about doing it here. There's a larger discussion around architecture for this operator happening at the moment. I won't link to a RH internal Jira here, but I think our users should be able to click on the Operator in "Installed Operators" and create their `OpenStackDataPlane` CR to define their compute infrastructure.

If this switch hides the operator from the console, does that mean they wouldn't be able to do this in that case? If so, I would be inclined to skip this change on the dataplane operator. Which would give the users a `OpenStackControlPlane` and a `OpenStackDataPlane` operator in their consoles to define the environment.

Please let me know if I'm misunderstanding this switch.

2023-07-11 10:49 UTC, fao89 commented
/test dataplane-operator-build-deploy-kuttl

2023-07-12 08:43 UTC, fao89 commented
/test dataplane-operator-build-deploy-kuttl

2023-07-12 08:45 UTC, fao89 commented
recheck

2023-07-24 12:23 UTC, slagle commented
> I'm not too sure about doing it here. There's a larger discussion around architecture for this operator happening at the moment. I won't link to a RH internal Jira here, but I think our users should be able to click on the Operator in "Installed Operators" and create their `OpenStackDataPlane` CR to define their compute infrastructure.
> 
> If this switch hides the operator from the console, does that mean they wouldn't be able to do this in that case? If so, I would be inclined to skip this change on the dataplane operator. Which would give the users a `OpenStackControlPlane` and a `OpenStackDataPlane` operator in their consoles to define the environment.
> 
> Please let me know if I'm misunderstanding this switch.

I believe this just hides dataplane-operator from the list of operators that can be installed in the console. The OpenStackDataPlane CRD still shows up in the UI when creating custom resources for openstack-operator. Its still in visibleCRDList in csv-merger.go

@dprince is that correct?

2023-07-24 16:21 UTC, fao89 commented
recheck

2023-07-24 19:49 UTC, dprince commented
@slagle has it correct. This is just "hidding" the Dataplane operator in the UI.

The Dataplane CRD here is being listed as a top level resource and should always remain visible at the top (even within the UI). Unless there has been a name change or something is misaligned I think we are still okay here: https://github.com/openstack-k8s-operators/openstack-operator/blob/main/cmd/csv-merger/csv-merger.go#L120

2023-07-24 19:51 UTC, fao89 commented
/override rdoproject.org/github-check

2023-07-24 21:58 UTC, bshephar commented
> @slagle has it correct. This is just "hidding" the Dataplane operator in the UI.
> 
> The Dataplane CRD here is being listed as a top level resource and should always remain visible at the top (even within the UI). Unless there has been a name change or something is misaligned I think we are still okay here: https://github.com/openstack-k8s-operators/openstack-operator/blob/main/cmd/csv-merger/csv-merger.go#L120

Right, so looks like it just hides it from the OperatorHub page specifically, not from the Installed Operators page, which is why my question was related to:
https://github.com/openshift/console/blob/682e0090ef91c73f0641e08d9280b25b48a43652/frontend/packages/operator-lifecycle-manager/src/components/operator-hub/operator-hub-page.tsx#L105-L109

Understand the requirement to hide it from OperatorHub, I'll clear my vote.

2023-07-24 21:58 UTC, bshephar approved these changes

2023-07-24 23:10 UTC, merged

2023-07-28 11:51 UTC, dprince commented
> @slagle has it correct. This is just "hidding" the Dataplane operator in the UI.
> 
> The Dataplane CRD here is being listed as a top level resource and should always remain visible at the top (even within the UI). Unless there has been a name change or something is misaligned I think we are still okay here: https://github.com/openstack-k8s-operators/openstack-operator/blob/main/cmd/csv-merger/csv-merger.go#L120

I need to clarify something that was incorrect about the 2nd half of my reply above. Because we no longer merge the dataplane CSV into openstack-operator (it is just pulled in as a dependency) we actually do need to handle this as a special case.

So... we could do as Brent suggested and leave dataplane-operator "visible" in the catalog. I'm not a huge fan of that as I think it is a bit confusing (you'll see 2 OpenStack operators, one depending on the other).

The other options would be: we could just merge in the dataplane CSV into openstack-operator. This would be much more lightweight than what we had before.

Lastly, we could move the CRDs, api/controllers for whatever dataplane stuff into openstack-operator.

Wanted to clarify things which I think have been broken since the last bundle split up.