Introduce dataplane-deployment-ceph-hci-pre
openstack-k8s-operators/dataplane-operator pull request #341
Opened 2023-08-08 17:17 UTC by fultonj

The ceph-hci-pre service calls the edpm-ansible role edpm_ceph_hci_pre to configure an EDPM node to host Ceph for collocation with Nova (HCI).

The deployer can shorten the services list to:

  - configure-network
  - validate-network
  - ceph-hci-pre

and then deploy Ceph out of band. After Ceph is deployed the full services list may be restored.

Jira: OSP-25827
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/273

2023-08-08 18:11 UTC, fao89 reviewed
+2

2023-08-09 07:37 UTC, rebtoor requested changes

2023-08-09 11:03 UTC, fmount commented
After @rebtoor's comment is addressed, I'll +2 the change that looks good.

2023-08-09 11:49 UTC, fultonj commented on config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
> +        import_role:
I could do that. Or based on what I see in https://github.com/openstack-k8s-operators/dataplane-operator/pull/326 I could just a call a new playbook I'm adding to the depends-on patch playbooks/ceph_hci_pre.yaml

2023-08-09 12:54 UTC, fultonj commented on config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
> +        import_role:
I tried to switch to `playbook` and rebased/recompiled my data plane operator but it didn't recognize any hosts.
```
[fultonj@hamfast scripts]$ oc logs -f dataplane-deployment-ceph-hci-pre-edpm-compute-8ltc8
Identity added: /runner/artifacts/dataplane-deployment-ceph-hci-pre-edpm-compute/ssh_key_data (fultonj@hamfast.examle.com)
No config file found; using defaults
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
[WARNING]: Could not match supplied host pattern, ignoring: []
[WARNING]: Could not match supplied host pattern, ignoring: overcloud

PLAY [Run Standalone Role] *****************************************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
Wednesday 09 August 2023  12:34:34 +0000 (0:00:00.030)       0:00:00.030 ****** 
=============================================================================== 
[fultonj@hamfast scripts]$ 
```

2023-08-09 12:56 UTC, fultonj commented on config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
> +        import_role:
It works with `import_role`.
```
[fultonj@hamfast dataplane-operator]$ cat config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
apiVersion: dataplane.openstack.org/v1beta1
kind: OpenStackDataPlaneService
metadata:
  name: ceph-hci-pre
spec:
  label: dataplane-deployment-ceph-hci-pre
  role:
    name: "Prepare EDPM to Host Ceph"
    hosts: "all"
    strategy: "linear"
    become: true
    tasks:
      - name: "Prepare EDPM to Host Ceph"
        import_role:
          name: "osp.edpm.edpm_ceph_hci_pre"
        tags:
          - "edpm_ceph_hci_pre"
[fultonj@hamfast dataplane-operator]$ oc delete -f config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
Error from server (NotFound): error when deleting "config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml": openstackdataplaneservices.dataplane.openstack.org "ceph-hci-pre" not found
[fultonj@hamfast dataplane-operator]$ oc create -f config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
openstackdataplaneservice.dataplane.openstack.org/ceph-hci-pre created
[fultonj@hamfast dataplane-operator]$ 
```
when I switch to `ansible.builtin.import_role` it doesn't work.
```
[fultonj@hamfast dataplane-operator]$ oc delete -f config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
openstackdataplaneservice.dataplane.openstack.org "ceph-hci-pre" deleted
[fultonj@hamfast dataplane-operator]$ 
[fultonj@hamfast dataplane-operator]$ git diff
diff --git a/config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml b/config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
index 633a237..93851a9 100644
--- a/config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
+++ b/config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
@@ -11,7 +11,7 @@ spec:
     become: true
     tasks:
       - name: "Prepare EDPM to Host Ceph"
-        import_role:
+        ansible.builtin.import_role:
           name: "osp.edpm.edpm_ceph_hci_pre"
         tags:
           - "edpm_ceph_hci_pre"
[fultonj@hamfast dataplane-operator]$ 
[fultonj@hamfast dataplane-operator]$ oc create -f config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
The OpenStackDataPlaneService "ceph-hci-pre" is invalid: spec.role.tasks[0].import_role: Required value
[fultonj@hamfast dataplane-operator]$ 
```

2023-08-09 13:05 UTC, rebtoor commented on config/services/dataplane_v1beta1_openstackdataplaneservice_ceph_hci_pre.yaml
> +        import_role:
My bad, `import_role` is correct in this context, i was thinking about ansible playbook, but here's is the implementation of the service.

See [here](https://github.com/openstack-k8s-operators/dataplane-operator/blob/35a3822017a78db6f62911bb7f3382a569314aa7/api/bases/dataplane.openstack.org_openstackdataplaneservices.yaml#L65)

2023-08-09 13:05 UTC, rebtoor approved these changes

2023-08-09 19:31 UTC, viroel commented
recheck

2023-08-09 20:19 UTC, viroel commented
recheck

2023-08-09 23:00 UTC, merged