WIP: OvS DPDK dataplane service sample files
openstack-k8s-operators/dataplane-operator pull request #536
Opened 2023-11-22 17:51 UTC by Jaganathancse

2024-01-19 19:24 UTC, Jaganathancse commented
recheck

2024-01-22 11:03 UTC, Jaganathancse commented
recheck

2024-01-23 07:01 UTC, Jaganathancse commented
recheck

2024-01-24 05:35 UTC, Jaganathancse commented
recheck

2024-02-06 10:01 UTC, jpodivin reviewed
There are some variables set that do not exist in the current RHOSO iteration. Furthermore the samples could use some documentation, either here, or in a linked PR somewhere else.

2024-02-06 10:01 UTC, jpodivin commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         edpm_ovn_dpdk_vhost_postcopy_support: "true"
ditto

2024-02-06 10:24 UTC, Jaganathancse commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         edpm_ovn_dpdk_memory_channels: "4"
same

2024-02-06 10:24 UTC, Jaganathancse commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         edpm_ovn_dpdk_socket_memory: "4096"
these are OvS DPDK rellated variables and already available in upstream.
https://github.com/openstack-k8s-operators/architecture/pull/80

2024-02-06 10:24 UTC, Jaganathancse commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         edpm_ovn_dpdk_vhost_postcopy_support: "true"
same

2024-02-06 10:25 UTC, Jaganathancse commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         neutron_public_interface_name: eth0
used this config sample based on https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/config/samples/dataplane_v1beta1_openstackdataplanenodeset_baremetal_with_ipam.yaml
also available in other few sample files.

2024-02-06 10:42 UTC, jpodivin commented on config/samples/dataplane_v1beta1_openstackdataplanenodeset_ovs_dpdk.yaml
> +         neutron_public_interface_name: eth0
That doesn't mean it's actually used by a role. Only that it's filled.

2024-02-06 10:43 UTC, jpodivin reviewed
Several parameters used in this sample are not actually used by edpm-ansible roles. They need to be either renamed, or the roles in edpm-ansible adjusted.

2024-02-06 10:44 UTC, jpodivin requested changes
Several parameters used in this sample are not actually used by edpm-ansible roles. They need to be either renamed, or the roles in edpm-ansible adjusted.

2024-02-06 10:51 UTC, Jaganathancse commented
> Several parameters used in this sample are not actually used by edpm-ansible roles. They need to be either renamed, or the roles in edpm-ansible adjusted.

These parameters are specific to OvS DPDK (role edpm_ovs_dpdk) and not common.
Also this Dataplane CR is the sample  to enable OvS DPDK on compute nodes similar like SRIOV.
will discuss and do a seperate PR for naming changes.

2024-02-06 14:12 UTC, jpodivin approved these changes

2024-02-06 14:32 UTC, fao89 approved these changes

2024-02-06 15:47 UTC, merged