Add kutl tests for TLS deployments
openstack-k8s-operators/dataplane-operator pull request #576
Opened 2023-12-13 23:37 UTC by vakwetu

2024-01-08 14:09 UTC, jpodivin requested changes
Fails while trying to convert yaml to struct.
`harness.go:394: loading /go/src/github.com/openstack-k8s-operators/dataplane-operator/tests/kuttl/tests/dataplane-deploy-tls-test/00-dataplane-create.yaml: error converting unstructured object TestStep:/ (/go/src/github.com/openstack-k8s-operators/dataplane-operator/tests/kuttl/tests/dataplane-deploy-tls-test/00-dataplane-create.yaml): error converting TestStep:/ from unstructured error: cannot restore slice from string`

2024-01-08 14:09 UTC, jpodivin commented on tests/kuttl/tests/dataplane-deploy-tls-test/00-dataplane-create.yaml
> +  oc deploy -f ./deploy/certs-create.yaml
I'm afraid you have to use `script` subfield for this.
https://kuttl.dev/docs/testing/steps.html#shell-scripts

2024-02-12 15:02 UTC, vakwetu commented
Closing --

2024-02-12 15:02 UTC, closed without merging

2024-02-12 15:02 UTC, vakwetu commented
superseded by https://github.com/openstack-k8s-operators/dataplane-operator/pull/651