Getting network name missing in dictiory issue
openstack-k8s-operators/dataplane-operator pull request #670
Opened 2024-02-15 02:45 UTC by Jaganathancse

This change is to fix network name missing issue during dataplane deployment.

2024-02-15 07:25 UTC, rabi requested changes
You don't need to add these as those would be auto generated. I've cleaned up the sample in https://github.com/openstack-k8s-operators/dataplane-operator/pull/671

2024-02-15 07:35 UTC, Jaganathancse commented
> You don't need to add these as those would be auto generated. I've cleaned up the sample in #671

Getting error due to Tenant network is unavailable in dict,
TASK [osp.edpm.edpm_network_config : Validating arguments against arg spec 'main' - The main entry point for the edpm_network_config role.] ***
Thursday 15 February 2024  01:49:59 +0000 (0:00:01.561)       0:00:10.449 ***** 
fatal: [edpm-compute-0]: FAILED! => {"msg": "'dict object' has no attribute 'Tenant'. 'dict object' has no attribute 'Tenant'"}

what could be the reason if no need to add manually?

2024-02-15 17:58 UTC, slagle approved these changes

2024-02-15 18:45 UTC, Jaganathancse commented
/retest-required

2024-02-16 04:30 UTC, Jaganathancse commented
recheck

2024-02-16 05:29 UTC, rabi approved these changes
/lgtm

2024-02-16 06:02 UTC, rabi commented
/lgtm

2024-02-16 07:30 UTC, merged