Replace samples with kustomize examples
openstack-k8s-operators/dataplane-operator pull request #698
Opened 2024-02-21 12:12 UTC by fao89

2024-02-21 12:14 UTC, fao89 commented
/test all

2024-02-21 13:19 UTC, fao89 commented
/test all

2024-02-21 18:46 UTC, fao89 commented
/test all

2024-02-21 22:50 UTC, slagle reviewed
I like the direction.
Instead of examples/base/openstackdataplanenodeset.yaml, can just make that use config/samples/dataplane_v1beta1_openstackdataplanenodeset.yaml? 

That would further remove duplication between the values.yaml and the sample.

I'd also like to get all fields that are just default values removed from the samples, so that they are minimal. We could have a single sample for each resource that documents all defaults as well.

2024-02-22 12:29 UTC, fao89 commented
> I like the direction. Instead of examples/base/openstackdataplanenodeset.yaml, can just make that use config/samples/dataplane_v1beta1_openstackdataplanenodeset.yaml?
> 

there is some customize logic for building the bundle, so I can't use `config/samples/dataplane_v1beta1_openstackdataplanenodeset.yaml`, what I can do is copy its content to `examples/base/openstackdataplanenodeset.yaml`

2024-02-22 19:04 UTC, fao89 commented
recheck

2024-02-23 01:10 UTC, fao89 commented
recheck

2024-02-23 10:58 UTC, fao89 commented
recheck

2024-02-23 13:13 UTC, fao89 commented
recheck

2024-02-27 10:44 UTC, fao89 commented
recheck

2024-02-27 12:59 UTC, fao89 commented
/test all

2024-02-27 13:09 UTC, fao89 commented
/retest-required

2024-02-27 15:11 UTC, fao89 commented
recheck

2024-02-27 19:39 UTC, fao89 commented
recheck

2024-02-27 19:43 UTC, fao89 commented
/test dataplane-operator-build-deploy-kuttl

2024-02-27 19:43 UTC, fao89 commented
recheck

2024-02-28 07:33 UTC, rabi commented on examples/baremetal/values.yaml
> +    networks:
Would not this create more issues and confusion as values.yaml has networks as a subkey in nodeset where as it maps to spec.nodeTemplate.networks?

2024-02-28 07:33 UTC, rabi commented on examples/bgp/values.yaml
> +      edpm-compute-0:
Do we need to repeat the `nodes` section as they're in the base? only the delta can be kustomized I assume. Also, we're now going to maintain 3 files for a sample and then the dependency on the base.

2024-02-28 13:53 UTC, jpodivin requested changes
I think documentation should be part of this PR. They target the same repo and make sense only together.

Plus if anything changes here you'll have to remember to make changes there.

2024-02-28 14:02 UTC, fao89 commented
> I think documentation should be part of this PR. They target the same repo and make sense only together.
> 
> Plus if anything changes here you'll have to remember to make changes there.

I don't want to make this PR bigger, I'll keep the other PR on hold until we merge this one

2024-02-28 20:26 UTC, fao89 commented
recheck

2024-02-28 21:27 UTC, fultonj reviewed
I am in favor of this proposed change.

For someone who only wants to refernce samples things change a little. Instead of looking directly at the samples [1] they can clone the repo and run kustomize and see the same thing. E.g. I can run `kustomize build examples/pre_ceph_hci/` and see the same outputs I would see if I clicked on [2] and [3].

This makes the samples much more maintainable as all the different examples can inherit from the base and duplicate data is replaced by references. 

I also see that for any change  in the new examples diretory, that you make sure kustomize can build it [4].

Thanks @fao89 

[1] https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/config/samples

[2] https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/config/samples/dataplane_v1beta1_openstackdataplanedeployment_pre_ceph_hci.yaml

[3] https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/config/samples/dataplane_v1beta1_openstackdataplanedeployment_pre_ceph_hci.yaml

[4] https://github.com/openstack-k8s-operators/dataplane-operator/actions/runs/8085585345/workflow?pr=698#L30-L33

2024-02-28 22:29 UTC, slagle reviewed
LGTM, +2
How do we intend to merge this? Just merge this PR and the install_yamls PR as close together as possible?

2024-02-29 08:48 UTC, fao89 commented
> LGTM, +2 How do we intend to merge this? Just merge this PR and the install_yamls PR as close together as possible?

I'll drop the breaking change on this PR, so it will be easier to coordinate with install_yamls

2024-02-29 14:10 UTC, fao89 commented
recheck

2024-02-29 17:14 UTC, slagle commented
recheck

https://github.com/openstack-k8s-operators/install_yamls/pull/752

2024-03-04 19:49 UTC, slagle reviewed
Can you restore:
config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp.yaml
config/samples/dataplane_v1beta1_openstackdataplanenodeset_bgp_ovn_cluster.yaml
config/samples/dataplane_v1beta1_openstackdataplanenodeset_networker.yaml
config/samples/dataplane_v1beta1_openstackdataplanedeployment_networker.yaml

that way we can merge this without breaking any part of install_yamls?

I think bumping the default KUSTOMIZE_VERSION to v5.0.1 in the Makefile is required as well, since this won't work with v3.8.7

2024-03-05 09:59 UTC, fao89 commented
I kept the samples that were needed on CI, the other samples is more for development and I believe it won't take long for https://github.com/openstack-k8s-operators/install_yamls/pull/743 to get merged

2024-03-05 15:32 UTC, slagle approved these changes

2024-03-05 16:47 UTC, merged