Add multiple cert support
openstack-k8s-operators/dataplane-operator pull request #875
Opened 2024-05-06 19:56 UTC by vakwetu

There will likely be a need to create multiple certs for a dataplane service.  This has already been raised as a use case
for libvirt to allow the better segregation of traffic.

This PR adds this capability, so that it can easily be exploited in future.  This will need a corresponding change in the edpm-ansible.

2024-05-06 19:57 UTC, vakwetu commented
hold to end of beta freeze

2024-05-09 04:06 UTC, vakwetu commented
/retest

2024-05-10 21:10 UTC, vakwetu commented
/retest

2024-05-15 08:17 UTC, jpodivin requested changes
minor nit, otherwise god. Do you think it deserves blocker status?

2024-05-20 18:00 UTC, vakwetu commented on pkg/deployment/cert.go
>  // openstack-epdm-nova-certs-0.
done!

2024-05-21 11:29 UTC, jpodivin approved these changes

2024-05-22 14:46 UTC, vakwetu commented
/unhold

2024-05-23 01:30 UTC, rabi commented
Are we adding functional/kuttl test coverage for this?

2024-05-23 20:51 UTC, vakwetu commented
@rabi  The kuttl tests were modified to validate the case where only one cert is defined (key=default).  Also, I just added some kuttl tests to validate the case where two certs are defined (key=default, key=second)

2024-05-29 19:50 UTC, slagle reviewed
+2

2024-06-03 14:15 UTC, fultonj commented
Can you ensure this is set correctly in ci-framework? 

https://github.com/openstack-k8s-operators/ci-framework/blob/e7210ad2020150fb63b1d006de930eee529ae601/roles/update_containers/templates/update_containers.j2#L2

2024-06-03 14:52 UTC, fao89 commented
recheck

2024-06-04 20:14 UTC, vakwetu commented
/retest

2024-06-04 20:14 UTC, vakwetu commented
recheck

2024-06-06 05:44 UTC, vakwetu commented
/retest

2024-06-06 05:45 UTC, vakwetu commented
recheck

2024-06-06 08:04 UTC, raukadah commented
recheck

2024-06-06 11:21 UTC, vakwetu commented
recheck

2024-06-06 13:30 UTC, rebtoor commented
/retest

2024-06-06 21:05 UTC, merged